name: KinkyDungeonApp
options:
  bundleIdPrefix: com.kinkydungeon
  deploymentTarget:
    iOS: "14.0"
targets:
  KinkyDungeonApp:
    type: application
    platform: iOS
    sources:
      - KinkyDungeonApp
    resources:
      - KinkyDungeonApp/www
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kinkydungeon.app
        TARGETED_DEVICE_FAMILY: 1,2
        INFOPLIST_FILE: KinkyDungeonApp/Info.plist
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGN_IDENTITY: ""
        SWIFT_VERSION: "5.0"
        SUPPORTS_MACCATALYST: NO
        IPHONEOS_DEPLOYMENT_TARGET: "14.0"
    dependencies: []
    cocoapods:
      enabled: true
    scheme:
      testTargets: []
